train_datasets:
  - dataset: "mozilla-foundation/common_voice_16_0"
    name: "hi"
    split: "train+validation+test"
    input_fields:
      - "audio"
      - "sentence"


eval_datasets:
  - dataset: "mozilla-foundation/common_voice_16_0"
    name: "hi"
    split: "other"
    input_fields:
      - "audio"
      - "sentence"

preprocessing:
  text:
    remove_special_characters: True
    lowercase: True
    remove_punctuation: True
    remove_latin_characters: False


pretrained_model_path: "./XEUS/model/xeus_checkpoint.pth"
train_batch_size: 4
eval_batch_size: 4
num_workers: 8
debug: False
result_path: "results"
exp_name: "hindi"
sampling_rate: 16000
warmup_steps: 100
learning_rate: 1e-4
save_steps: 1000
eval_step: 100
validation_steps: 20
logging_steps: 10
save_total_limit: 2
push_to_hub: False
gradient_checkpointing: True
total_steps: 5000
gradient_accumulation_steps: 4
ckpt_path: ""